IntelLabs/kafl.fuzzer

kafl_cov.py, kafl_fuzzer/common/util.py, kafl_fuzzer/debug/core.py, kafl_fuzzer/manager/core.py
The options are fundamentally incompatible and result in Qemu launch error. Also harmonize how initialization and error handling is done across fuzz/cov/debug tools.
=> abort if both --resume and --purge are given

kafl.yaml, kafl_fuzzer/common/config.py
This allows to override or completely remove the qemu -append and -serial options via appropriate kafl.yaml
=> turn hardcoded serial and append params into default config values

kafl_fuzzer/common/util.py, kafl_fuzzer/manager/core.py, kafl_fuzzer/worker/worker.py
Individual workers now pick the Nth item out of currently configured CPU set rather than overriding an existing config. This allows to limit the cpu set more flexibly by the parent, e.g. using taskset.
Additionally, before starting the workers, the manager now performs a scan for other Qemu instances in the system and removes their respective pinned CPUs from the own available set.
Together, this should avoid the need for manually checking available CPUs and defining --cpu-offset for kafl_fuzz.py
=> Smarter CPU affinity selection

scripts/ghidra_run.sh
When used in a pipeline, errors may not be visilbe on stdout..
=> ghidra_run.sh: fail to stderr

kafl_fuzzer/tests/test_deterministic.py, kafl_fuzzer/tests/test_havoc_handler.py
- changed bitmap loading broke the tests
- adding helper_init() to global scope makes it work
$ make env
$ cd $KAFL_ROOT/fuzzer
$ pip install pytest
$ make test
$ make benchmark
=> tests: initialize mutation helper non-class for pytest

kafl_fuzzer/common/util.py, kafl_fuzzer/manager/core.py
- when the set of free cpus is empty, previous code died already when attempting to set the affinity in filter_available_cpus()
- warn but do not abort if auto-detection indicates that available cpus are already occupied. it could be zombies or debug instances..
=> cpu affinity: try to continue even if cpus seem busy

kafl_fuzzer/manager/core.py
The --cpu-offset arugment was incompatible with automated detection of free/busy CPUs. The reduced cpu set is not obvious during startup time and we may fail to launch workers if cpu set + cpu offset < workers.
This patch disables auto-detection of free vcpus if a --cpu-offset is given. This restores the original semantics of --cpu-offset.
=> cpu affinity: consider --cpu-offset as override to auto-detection

kafl_fuzzer/manager/communicator.py, kafl_fuzzer/manager/manager.py, kafl_fuzzer/worker/qemu.py
This prevents printing fuzzer status line when actually still waiting for Workers/Qemu to boot.
It also detects when Qemu instances abort/exit, in particular the first Worker may abort and others never become READY due to missing created snapshot image. Previously, the manager would just keep waiting for other Workers to come online.
In detail:
- on ABORT hypercall and/or QemuIOException, let workers send ABORT msg to manager thread
- also send ABORT on Qemu startup to catch exit due to malformed qemu cmdline etc.
- update manager to keep track of READY vs ABORTed workers
- do not print status line before first worker has become ready
(this leaves the previous printed status messages, "waiting for snapshot" or "waiting for VM to start")
- once at least one Worker has become ready …
=> improve startup/failure reporting of Worker instances

kafl_fuzzer/manager/manager.py, kafl_fuzzer/worker/qemu.py, kafl_fuzzer/worker/worker.py
This improves on #25 which was not handling errors during qemu.start() phase. In this case, the Worker-00 will typically not create the snapshot, which leads all other Workers to wait forever on snapshot creation.
Fix:
- on Qemu ABORT event or any other qemu.start() failure, let Worker send ABORT to manager
- in manager, if no Workers are ready but someone has aborted, exit and kill them all.
- also, use qemu.async_exit() to avoid duplicate execution of qemu.shutdown()
=> also detect qemu.start() failure and avoid double-shutdown

kafl_fuzzer/worker/qemu.py
This allows to redirect qemu log output based on recent QemuNyx changes.
When building QemuNyx in debug mode, additional output can be produced via the 'nyx' log facility.
Enable this by default when --log is given.
=> qemu.py: redirect qemu outputs on --log

.github/RELEASE.md, .github/workflows/ci.yml
- add `.github/RELEASE.md`  to be filled with release details.
- add `release` job depending on `lint` job and tag having `v*` pattern
=> CI: add release job triggered by v* tags

.github/RELEASE.md, kafl_fuzzer/worker/qemu.py
Do not release the Qemu mutex after habort() / nyx_abort(). Normally this should lead to Qemu exit(1) but its blocking when the abort comes in before handshake. Keeping the mutex seems to work fine.
=> remove qemu_run() from USER_ABORT handler

.github/RELEASE.md, setup.py
`default_settings.yaml` was not included in the installed kafl_fuzzer package
=> setup: fix including default_settings.yaml in the final distribution

.github/RELEASE.md, kafl_fuzzer/__main__.py, kafl_fuzzer/common/config/cmdline.py, kafl_fuzzer/common/logger.py, kafl_fuzzer/coverage/__init__.py, kafl_fuzzer/debug/core.py, kafl_fuzzer/manager/core.py
I refactored the `logger.py` to split the main `setup_logging()` function into 2 functions
- `load_logging_config()`: simply loads the `logging.yaml` config file, and store it in a global variable
- `setup_basic_logging()`: setup console, useful to log loaded configuration before validation happens
- `add_file_logging()`: add `$WORKDIR/kafl_fuzzer.log` if `--log` has been specified
Finally I dump all possible info I could find about the loaded kAFL configuration, in order to simplify detecting config issues.
First: `Loaded configuration files`
Second: `Command line configuration`
Third `Loaded configuration values` (Dynaconf loaded values, either from env vars (matching `KAFL_`) or config files)
And finally the final config after validation:
=> fuzzer: refactor logging to dump state of loaded config before validation

kafl_fuzzer/common/config/default_settings.yaml
Set a default value for `debug` in configuration files since the validator have not been executed by the time the key is being used in `cmdline.py:hidden()`
=> default_settings: set debug value

kafl_fuzzer/common/self_check.py, kafl_fuzzer/manager/bitmap.py, kafl_fuzzer/native/Makefile, kafl_fuzzer/native/loader.py
Load `bitmap.so` only using the compiled version by `setup.py` 's `Extension` module.
Don't use the custom `Makefile` at runtime to compile it, and remove that code anyway.
Also remove check if the library is compiled, since it will be compiled by `setup.py`
=> fuzzer: use bitmap.so compiled as Extension by setup.py

kafl_fuzzer/common/config/default_settings.yaml
`setup_basic_logging()` is checking for these values before the validation happens.
These needs to be set in the default config file
=> config: set default values in the config for quiet and verbose

kafl_fuzzer/common/config/cmdline.py, kafl_fuzzer/common/config/default_settings.yaml, kafl_fuzzer/common/config/settings.py, kafl_fuzzer/common/logger.py, kafl_fuzzer/common/util.py, kafl_fuzzer/coverage/__init__.py, kafl_fuzzer/debug/core.py, kafl_fuzzer/gui/__init__.py, kafl_fuzzer/manager/bitmap.py, kafl_fuzzer/manager/communicator.py, kafl_fuzzer/manager/core.py, kafl_fuzzer/manager/manager.py, kafl_fuzzer/manager/node.py, kafl_fuzzer/manager/statistics.py, kafl_fuzzer/plot/__init__.py, kafl_fuzzer/technique/havoc.py, kafl_fuzzer/technique/radamsa.py, kafl_fuzzer/technique/redqueen/workdir.py, kafl_fuzzer/worker/qemu.py, kafl_fuzzer/worker/worker.py
I think we want to suport the existing KAFL_WORKDIR variable used in several scripts + docs so far. It is at odds with the --work-dir argument but they are established now and actually easier to type than KAFL_WORK_DIR.
I tried the previous proposed option:
>    Validator("workdir", must_exist=True, cast=cast_expand_path_no_verify),
>   Validator("work_dir", must_exist=True, default=lambda config, _validator: config.workdir),
However, the default= action is only called if the option was not set. There seem to be no other available API hooks so we cannot easily create an alias like this.
So this patch replaces all instances of work_dir with workdir.  argparse -w --work-dir options now set the workdir variable, and they got an additional alias --workdir so there is a path to make this …
=> config: support existing KAFL_WORKDIR override

kafl_fuzzer/common/util.py
Avoid these types of errors:
~~~python
qemu-system-x86_64: terminating on signal 15 from pid 12 (kafl)
Traceback (most recent call last):
File "stub.py", line 2, in <module>
File "kafl_fuzzer/__main__.py", line 34, in main
File "kafl_fuzzer/manager/core.py", line 114, in start
File "kafl_fuzzer/common/util.py", line 38, in qemu_sweep
File "kafl_fuzzer/common/util.py", line 38, in <listcomp>
File "kafl_fuzzer/common/util.py", line 34, in get_qemu_processes
File "getpass.py", line 169, in getuser
KeyError: 'getpwuid(): uid not found: 2009'
~~~
related to https://github.com/IntelLabs/kAFL/pull/104
=> util: skip QEMU sweep when running inside container

kafl_fuzzer/worker/qemu.py
Full qemu logging requires compiling for debug, but either way we should not enable it directly on --log.
=> qemu.py: enable Qemu verbose debug only on --log && --debug

.github/RELEASE.md, kafl_fuzzer/common/config/settings.py
This PR removes the Path checking on `qemu_image` parameter.
In fact, this parameter can be a complex drive description, and not just a file as we assumed.
For example, If I want to specify a qcow image that should be attached with the `virtio` interface:
`--image /home/user/myqemyimage.qcow2,if=virtio`
Without the fix:
```python
Traceback (most recent call last):
File "/home/mtarral/kafl/kafl/.venv/bin/kafl", line 11, in <module>
load_entry_point('kafl-fuzzer', 'console_scripts', 'kafl')()
File "/home/mtarral/kafl/kafl/fuzzer/kafl_fuzzer/__main__.py", line 30, in main
validate()
File "/home/mtarral/kafl/kafl/fuzzer/kafl_fuzzer/common/config/settings.py", line 184, in validate
settings.validators.validate()
File "/home/mtarral/kafl/kafl/.venv/lib/python3.8/site-packages/dynaconf/validator. …
```
=> settings: don't force qemu_image to be a path

kafl_fuzzer/common/config/settings.py, kafl_fuzzer/common/logger.py, kafl_fuzzer/coverage/__init__.py, kafl_fuzzer/manager/core.py, kafl_fuzzer/manager/manager.py, kafl_fuzzer/worker/qemu.py, requirements.txt
This PR parses the range submit info dumped by https://github.com/IntelLabs/kafl.qemu/pull/10 on fuzzer shutdown.
It then updates his own configuration and dumps it the known `WORKDIR/config.yaml` config file.
`kafl cov` has been updated to load this additional config file at startup, and only refresh its IP filters config.
This allows to transparently launch `kafl cov` on an existing workdir, and removes manual user configuration, and dumping unstructured data through hprintf logs.
=> Parse range submit

.github/RELEASE.md, kafl_fuzzer/common/config/cmdline.py, kafl_fuzzer/common/config/settings.py
The `action` argument is only used by the `debug` subcommand.
Furthermore, it's a required argument that should be constrained by the command line when invoking the `debug` subcommand.
This PR updates the cmdline parser so that the `action` argument will only be added to the `debug` options subgroup.
kafl cov --help:
kafl debug --help:
kafl debug:
=> config: move action as required argument for debug subcommand only

kafl_fuzzer/common/util.py
fix https://github.com/IntelLabs/kafl.fuzzer/pull/73
=> util: fix None value in find_diffs

kafl_fuzzer/common/config/default_settings.yaml, kafl_fuzzer/common/config/settings.py, kafl_fuzzer/worker/qemu.py
This PR solves https://github.com/IntelLabs/kafl.fuzzer/issues/64 by only setting the `qemu_append` when `qemu_kernel` was already defined, based on a default setting.
=> config: set qemu_append only when qemu_kernel is defined

kafl_fuzzer/manager/manager.py
Fix https://github.com/IntelLabs/kAFL/issues/298
This appears to happen when the target is slow and the manager tries to check for initial coverage? It can also happen when using multiple instances. The commit fixes the incorrect required type for `mm3.hash`.
=> Fix wrong type for main_bitmap

kafl_fuzzer/worker/execution_result.py
Another fix following https://github.com/IntelLabs/kAFL/issues/298 and #81
=> worker: fix mmh3.hash64 argument by converting to bytes
